### ISSUE TITLE
Fails to build on ubuntu 18.04

### ISSUE THREAD

**Issue by ihor-nahuliak** [joto/osmium#102]
```
$ make
g++ -O3 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I../include -I/usr/include/libshp -DOSMIUM_WITH_DEBUG -I/usr/include -Wall -Wextra -Wdisabled-optimization -pedantic -Wctor-dtor-privacy -Wnon-virtual-dtor -Woverloaded-virtual -Wsign-promo -Wno-long-long -o osmjs osmjs.cpp  -lexpat -lz -lpthread -lprotobuf-lite -losmpbf -lv8 -licuuc -lshp -L/usr/lib/x86_64-linux-gnu -lgeos-3.6.2
In file included from ../include/osmium/javascript/wrapper/position.hpp:27:0,
                 from ../include/osmium/javascript/handler.hpp:31,
                 from ../include/osmium/javascript.hpp:27,
                 from osmjs.cpp:30:
../include/osmium/javascript/unicode.hpp: In function ‘void Osmium::v8_String_to_ostream(v8::Local<v8::String>, std::ostream&)’:
../include/osmium/javascript/unicode.hpp:136:87: error: invalid conversion from ‘uint16_t* {aka short unsigned int*}’ to ‘const UChar* {aka const char16_t*}’ [-fpermissive]
         u_strToUTF8(buffer, length, &buffer_length, src, string->Length(), &error_code);
                                                                                       ^
In file included from /usr/include/unicode/platform.h:25:0,
                 from /usr/include/unicode/ptypes.h:52,
                 from /usr/include/unicode/umachine.h:46,
                 from /usr/include/unicode/utypes.h:38,
                 from /usr/include/unicode/ustring.h:21,
                 from ../include/osmium/javascript/unicode.hpp:29,
                 from ../include/osmium/javascript/wrapper/position.hpp:27,
                 from ../include/osmium/javascript/handler.hpp:31,
                 from ../include/osmium/javascript.hpp:27,
                 from osmjs.cpp:30:
/usr/include/unicode/ustring.h:1267:1: note:   initializing argument 4 of ‘char* u_strToUTF8_60(char*, int32_t, int32_t*, const UChar*, int32_t, UErrorCode*)’
 u_strToUTF8(char *dest,
 ^
In file included from ../include/osmium/geometry/multipolygon.hpp:34:0,
                 from ../include/osmium/javascript/wrapper/geometry.hpp:39,
                 from ../include/osmium/javascript/handler.hpp:32,
                 from ../include/osmium/javascript.hpp:27,
                 from osmjs.cpp:30:
../include/osmium/geometry/geos.hpp: In function ‘geos::geom::GeometryFactory* Osmium::Geometry::geos_geometry_factory()’:
../include/osmium/geometry/geos.hpp:54:63: error: ‘geos::geom::GeometryFactory::GeometryFactory(const geos::geom::PrecisionModel*, int)’ is protected within this context
             static geos::geom::GeometryFactory factory(&pm, -1);
                                                               ^
In file included from ../include/osmium/geometry/geos.hpp:28:0,
                 from ../include/osmium/geometry/multipolygon.hpp:34,
                 from ../include/osmium/javascript/wrapper/geometry.hpp:39,
                 from ../include/osmium/javascript/handler.hpp:32,
                 from ../include/osmium/javascript.hpp:27,
                 from osmjs.cpp:30:
/usr/include/geos/geom/GeometryFactory.h:464:2: note: declared protected here
  GeometryFactory(const PrecisionModel* pm, int newSRID);
  ^~~~~~~~~~~~~~~
In file included from ../include/osmium/geometry/multipolygon.hpp:34:0,
                 from ../include/osmium/javascript/wrapper/geometry.hpp:39,
                 from ../include/osmium/javascript/handler.hpp:32,
                 from ../include/osmium/javascript.hpp:27,
                 from osmjs.cpp:30:
../include/osmium/geometry/geos.hpp:54:63: error: ‘virtual geos::geom::GeometryFactory::~GeometryFactory()’ is protected within this context
             static geos::geom::GeometryFactory factory(&pm, -1);
                                                               ^
In file included from ../include/osmium/geometry/geos.hpp:28:0,
                 from ../include/osmium/geometry/multipolygon.hpp:34,
                 from ../include/osmium/javascript/wrapper/geometry.hpp:39,
                 from ../include/osmium/javascript/handler.hpp:32,
                 from ../include/osmium/javascript.hpp:27,
                 from osmjs.cpp:30:
/usr/include/geos/geom/GeometryFactory.h:474:10: note: declared protected here
  virtual ~GeometryFactory();
          ^
In file included from ../include/osmium/javascript/handler.hpp:35:0,
                 from ../include/osmium/javascript.hpp:27,
                 from osmjs.cpp:30:
../include/osmium/javascript/wrapper/export_shapefile.hpp: In static member function ‘static void Osmium::Javascript::Wrapper::ExportShapefile::add_string_attribute(Osmium::Export::Shapefile*, int, v8::Local<v8::Value>)’:
../include/osmium/javascript/wrapper/export_shapefile.hpp:69:191: error: invalid conversion from ‘uint16_t* {aka short unsigned int*}’ to ‘const UChar* {aka const char16_t*}’ [-fpermissive]
                     u_strToUTF8(dest, shapefile->field(n).width(), &dest_length, source, std::min(Osmium::Export::Shapefile::max_dbf_field_length+1, value->ToString()->Length()), &error_code);
                                                                                                                                                                                               ^
In file included from /usr/include/unicode/platform.h:25:0,
                 from /usr/include/unicode/ptypes.h:52,
                 from /usr/include/unicode/umachine.h:46,
                 from /usr/include/unicode/utypes.h:38,
                 from /usr/include/unicode/ustring.h:21,
                 from ../include/osmium/javascript/unicode.hpp:29,
                 from ../include/osmium/javascript/wrapper/position.hpp:27,
                 from ../include/osmium/javascript/handler.hpp:31,
                 from ../include/osmium/javascript.hpp:27,
                 from osmjs.cpp:30:
/usr/include/unicode/ustring.h:1267:1: note:   initializing argument 4 of ‘char* u_strToUTF8_60(char*, int32_t, int32_t*, const UChar*, int32_t, UErrorCode*)’
 u_strToUTF8(char *dest,
 ^
In file included from ../include/osmium/javascript/wrapper/position.hpp:27:0,
                 from ../include/osmium/javascript/handler.hpp:31,
                 from ../include/osmium/javascript.hpp:27,
                 from osmjs.cpp:30:
../include/osmium/javascript/unicode.hpp: In instantiation of ‘const char* Osmium::v8_String_to_utf8(v8::Local<v8::String>) [with int characters = 512]’:
../include/osmium/javascript/wrapper/osm.hpp:46:113:   required from here
../include/osmium/javascript/unicode.hpp:108:20: error: invalid conversion from ‘uint16_t* {aka short unsigned int*}’ to ‘const UChar* {aka const char16_t*}’ [-fpermissive]
         u_strToUTF8(buffer, characters*4, &buffer_length, src, std::min(characters*2, string->Length()), &error_code);
                    ^
In file included from /usr/include/unicode/platform.h:25:0,
                 from /usr/include/unicode/ptypes.h:52,
                 from /usr/include/unicode/umachine.h:46,
                 from /usr/include/unicode/utypes.h:38,
                 from /usr/include/unicode/ustring.h:21,
                 from ../include/osmium/javascript/unicode.hpp:29,
                 from ../include/osmium/javascript/wrapper/position.hpp:27,
                 from ../include/osmium/javascript/handler.hpp:31,
                 from ../include/osmium/javascript.hpp:27,
                 from osmjs.cpp:30:
/usr/include/unicode/ustring.h:1267:1: note:   initializing argument 4 of ‘char* u_strToUTF8_60(char*, int32_t, int32_t*, const UChar*, int32_t, UErrorCode*)’
 u_strToUTF8(char *dest,
 ^
In file included from ../include/osmium/javascript/wrapper/position.hpp:27:0,
                 from ../include/osmium/javascript/handler.hpp:31,
                 from ../include/osmium/javascript.hpp:27,
                 from osmjs.cpp:30:
../include/osmium/javascript/unicode.hpp: In instantiation of ‘v8::Local<v8::String> Osmium::utf8_to_v8_String(const char*) [with int characters = 512]’:
../include/osmium/javascript/wrapper/osm.hpp:49:105:   required from here
../include/osmium/javascript/unicode.hpp:90:31: error: invalid conversion from ‘UChar* {aka char16_t*}’ to ‘const uint16_t* {aka const short unsigned int*}’ [-fpermissive]
         return v8::String::New(dest, dest_length);
                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
In file included from ../include/osmium/javascript/handler.hpp:28:0,
                 from ../include/osmium/javascript.hpp:27,
                 from osmjs.cpp:30:
/usr/include/v8.h:1229:33: note:   initializing argument 1 of ‘static v8::Local<v8::String> v8::String::New(const uint16_t*, int)’
   V8EXPORT static Local<String> New(const uint16_t* data, int length = -1);
                                 ^~~
Makefile:43: recipe for target 'osmjs' failed
make: *** [osmjs] Error 1
```

**Comment by joto** [comment]
This software is really really old and is not supported any more. You almost certainly want the "new" Osmium at http://osmcode.org/

**Comment by ihor-nahuliak** [comment]
I just wanted to run polygons convertation script https://github.com/mapbox/osm-boundaries which in his dependencies this script has.

**Comment by dottorblaster** [comment]
@joto I'm sorry to bother but... what if someone needs `osmjs` on recent systems?

**Comment by joto** [comment]
@dottorblaster Then they are on their own. I recommend using PyOsmium instead.
